[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"
authors = ["Nathaniel Nasarow"]

[dependencies]
bracket-lib = { version = "0.8.7"}
specs = "0.20.0"
specs-derive = "0.4.1"

[workspace]

